import Link from "next/link";
import {ArrowRight,Truck,ShieldCheck,RotateCcw,ChevronRight,Quote} from "lucide-react";
import {products,categories} from "@/data/products";
import {ProductCard} from "@/components/product-card";
import {AudiencePromos} from "@/components/audience-promos";
import {ProductCarousel} from "@/components/product-carousel";
import {HeroCarousel} from "@/components/hero-carousel";
const catIcons=["⌨","🖱","🎧","🎮","▣","♜","▰","⚙"];
const benefits=[{icon:Truck,title:"Free standard delivery",detail:"3–5 business days"},{icon:ShieldCheck,title:"2-year warranty",detail:"Official coverage"},{icon:RotateCcw,title:"Easy returns",detail:"Within 14 days"},{icon:ShieldCheck,title:"Secure checkout",detail:"Shop with confidence"}];
const heroProducts=[0,3,6,9,11,14,16,18,1].map(index=>products[index]);

export default function Home(){return <>
<HeroCarousel items={heroProducts}/>
<div className="border-b border-[#202633]"><div className="container grid grid-cols-2 gap-5 py-5 md:grid-cols-4">{benefits.map(({icon:I,title,detail})=><div className="flex items-center gap-3" key={title}><I className="text-[#77e5ad]" size={21}/><div><b className="block text-sm">{title}</b><span className="muted text-xs">{detail}</span></div></div>)}</div></div>
<section id="categories" className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Find your gear</p><h2>Shop by category</h2></div><Link href="/shop" className="muted flex items-center gap-1 text-sm hover:text-white">View all <ChevronRight size={16}/></Link></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{categories.map((x,i)=><Link href={`/shop?category=${encodeURIComponent(x)}`} key={x} className="panel group flex items-center gap-4 p-5 hover:-translate-y-1 hover:border-[#405044]"><span className="grid h-12 w-12 place-items-center rounded-xl bg-white/5 text-2xl group-hover:bg-[#77e5ad] group-hover:text-black">{catIcons[i]}</span><div><b>{x}</b><p className="muted text-xs">{products.filter(p=>p.category===x).length} products</p></div></Link>)}</div></div></section>
<ProductSection title="Trending gear" label="Player favorites" items={products.slice(0,8)}/><section id="new"><ProductSection title="Fresh arrivals" label="Just landed" items={products.filter(p=>p.newArrival).slice(0,4)}/></section><section id="deals"><ProductSection title="Deals of the week" label="Limited time" items={products.filter(p=>p.oldPrice).slice(0,4)}/></section>
<section className="section"><div className="container panel relative overflow-hidden bg-[#101b17] p-8 md:p-14"><div className="relative z-10 max-w-xl"><p className="eyebrow">Your desk. Your rules.</p><h2 className="mt-3 text-4xl font-black sm:text-5xl">Build a setup that feels uniquely yours.</h2><p className="muted mt-5 leading-7">Pick compatible gear, see the total instantly, and add your entire dream setup to cart in one click.</p><Link href="/build-your-setup" className="btn primary mt-7">Start building <ArrowRight size={18}/></Link></div><div className="absolute -bottom-32 -right-24 h-96 w-96 rounded-full bg-[#77e5ad]/10 blur-2xl"/></div></section>
<section className="section border-y border-[#202633] bg-[#0c1016]"><div className="container"><p className="eyebrow text-center">Trusted by players</p><h2 className="mt-2 text-center text-4xl font-black">Real setups. Real stories.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{[["The product curation is excellent. My desk finally feels cohesive—and everything arrived ahead of schedule.","Mika R."],["Clean buying experience, fast delivery, and the keyboard feels incredible. KADA Tech is now my first stop.","Paolo D."],["Building a complete setup was surprisingly easy. Great prices without compromising on premium brands.","Aly S."]].map(x=><blockquote className="panel p-6" key={x[1]}><Quote className="text-[#77e5ad]"/><p className="mt-5 leading-7 text-gray-300">“{x[0]}”</p><b className="mt-5 block">{x[1]}</b><span className="text-sm text-amber-400">★★★★★</span></blockquote>)}</div></div></section>
<AudiencePromos/><section className="section"><div className="container text-center"><p className="eyebrow">Stay in the loop</p><h2 className="mt-2 text-4xl font-black">Get first dibs on new gear.</h2><p className="muted mx-auto mt-3 max-w-xl">Product drops, setup inspiration, and members-only offers. No clutter.</p><form className="mx-auto mt-7 flex max-w-lg gap-2"><input className="field" type="email" placeholder="you@email.com" aria-label="Email"/><button className="btn primary">Join</button></form></div></section>
</>}
function ProductSection({title,label,items}:{title:string;label:string;items:typeof products}){const carousel=title==="Trending gear";return <section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">{label}</p><h2>{title}</h2></div><Link href="/shop" className="muted text-sm">View all →</Link></div>{carousel?<ProductCarousel items={items}/>:<div className="grid-products">{items.map(p=><ProductCard p={p} key={p.id}/>)}</div>}</div></section>}
