"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { Check, ChevronLeft, ChevronRight, ImagePlus, Link2, Nfc, QrCode, Trash2, Upload } from "lucide-react";
import { useStore } from "@/components/store";
import { peso } from "@/lib/helpers";
import { NFCCustomization, NFCProductType } from "@/types";
import { NFC_PRICES, studentPrice } from "@/data/pricing";

const products:{id:NFCProductType;name:string;price:number;description:string;colors:string[];styles:string[]}[]=[
 {id:"card",name:"KADA Custom NFC Card",price:NFC_PRICES.card,description:"Your identity, portfolio, business card, music, or social profile.",colors:["Obsidian Black","Pearl White","KADA Green"],styles:["Matte","Gloss"]},
 {id:"bracelet",name:"KADA NFC Bracelet",price:NFC_PRICES.bracelet,description:"Wearable connection for music, gifts, events, and contact sharing.",colors:["Black","Forest","White","Rose"],styles:["Silicone","Woven"]},
 {id:"keychain",name:"KADA NFC Keychain",price:NFC_PRICES.keychain,description:"A compact personal, business, luggage, or couple tag.",colors:["Black","Green","Silver"],styles:["Round","Rectangle"]},
 {id:"tag",name:"KADA NFC Tag",price:NFC_PRICES.tag,description:"Personal ID, pet, luggage, or emergency contact tag.",colors:["Black","White","Green"],styles:["Round","Shield"]},
 {id:"stand",name:"KADA NFC Desk Stand",price:NFC_PRICES.stand,description:"Invite customers to view, review, follow, or save with one tap.",colors:["Black","White","Walnut"],styles:["Portrait","Landscape"]},
 {id:"premium-card",name:"KADA Premium NFC Card",price:NFC_PRICES.premiumCard,description:"Premium material with full personalization included.",colors:["Metal Black","Silver"],styles:["Metal","Premium Matte"]},
 {id:"couple",name:"KADA Couple NFC Bracelets",price:NFC_PRICES.couple,description:"A personalized pair linked to a shared song or page.",colors:["Black + Black","Black + Rose"],styles:["Silicone Pair"]},
 {id:"pet",name:"KADA NFC Pet Tag",price:NFC_PRICES.pet,description:"Personalized pet tag linked to owner contact details.",colors:["Black","Green","Rose"],styles:["Bone","Round"]},
];
const destinations=["Business Information","Spotify / Music","Social Media","Portfolio","Website","Contact Information","Digital Menu","Review Page","Personal / Gift Link","Custom URL"];
const steps=["Choose Product","Design It","NFC Setup","Preview","Add to Cart"];
const blank:NFCCustomization={productType:"card",productName:"KADA Custom NFC Card",unitPrice:NFC_PRICES.card,color:"Obsidian Black",style:"Matte",name:"",title:"",company:"",text:"",initials:"",symbol:"None",background:"Midnight",alignment:"left",font:"Modern",qrCode:false,side:"front",imageScale:100,imageX:50,imageY:50,setup:"kada",destinationType:"Website",destinationUrl:"",programmingFields:{}};

export function NFCStudio(){
 const {addCustomNfc}=useStore();
 const [step,setStep]=useState(0),[data,setData]=useState<NFCCustomization>(blank),[error,setError]=useState(""),[hydrated,setHydrated]=useState(false);
 useEffect(()=>{try{const saved=localStorage.getItem("kada-nfc-draft");if(saved)setData({...blank,...JSON.parse(saved),imageDataUrl:undefined});}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem("kada-nfc-draft",JSON.stringify({...data,imageDataUrl:undefined}))},[data,hydrated]);
 const product=products.find(p=>p.id===data.productType)!;
 const update=(next:Partial<NFCCustomization>)=>{setData(v=>({...v,...next}));setError("")};
 const choose=(id:NFCProductType)=>{const p=products.find(x=>x.id===id)!;update({productType:id,productName:p.name,unitPrice:p.price,color:p.colors[0],style:p.styles[0],name:"",title:"",company:"",text:"",initials:"",imageName:undefined,imageDataUrl:undefined})};
 const validUrl=()=>{if(data.setup==="self")return true;try{const u=new URL(data.destinationUrl);return u.protocol==="https:"}catch{return false}};
 const next=()=>{if(step===2&&!validUrl()){setError("Enter a valid HTTPS destination before continuing.");return}setStep(v=>Math.min(4,v+1));window.scrollTo({top:0,behavior:"smooth"})};
 const add=()=>{if(!validUrl()){setStep(2);setError("Enter a valid HTTPS destination before adding this item.");return}addCustomNfc(data);localStorage.removeItem("kada-nfc-draft")};
 return <div>
  <header className="border-b border-[#202633] bg-[radial-gradient(circle_at_75%_20%,rgba(119,229,173,.14),transparent_32%)]">
   <div className="container py-12 md:py-16"><p className="eyebrow">KADA Custom NFC</p><h1 className="mt-3 max-w-3xl text-4xl font-black leading-tight sm:text-6xl">Design it. Tap it. Make it yours.</h1><p className="muted mt-5 max-w-2xl text-lg leading-8">Customize the look, choose what happens when it is tapped, and get free NFC programmingor program it yourself anytime.</p><div className="mt-6 inline-flex items-center gap-2 rounded-full border border-[#29523e] bg-[#173225] px-4 py-2 text-sm font-bold text-[#8befbd]"><Nfc size={18}/> No programming fee. No complicated setup.</div></div>
  </header>
  <section id="how-it-works" className="scroll-mt-28 border-b border-[#202633] bg-[#0c1016]" aria-labelledby="how-it-works-title"><div className="container py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">How it works</p><h2 id="how-it-works-title" className="mt-2 text-3xl font-black">From your idea to one useful tap.</h2></div><button onClick={()=>{setStep(0);document.getElementById("nfc-customizer")?.scrollIntoView({behavior:"smooth"})}} className="btn primary">Start customizing <ChevronRight size={17}/></button></div><div className="mt-7 grid gap-4 md:grid-cols-3">{[["1","Design It","Choose a product, color, text, and optional photo, logo, artwork, or QR code."],["2","Connect It","Program it yourself or provide an HTTPS link and let KADA program it for free."],["3","Tap It","After delivery, tap with a compatible phone to open the saved business, music, social, or custom link."]].map(([number,title,copy])=><article className="panel p-5" key={number}><span className="grid h-9 w-9 place-items-center rounded-full bg-[#173225] font-black text-[#77e5ad]">{number}</span><h3 className="mt-4 font-bold">{title}</h3><p className="muted mt-2 text-sm leading-6">{copy}</p></article>)}</div><p className="muted mt-5 text-xs">The website collects your customization and programming instructions. It does not write NFC chips in the browser.</p></div></section>
  <div id="nfc-customizer" className="container scroll-mt-28 py-8">
   <Progress step={step}/>
   <div className="mt-8 grid items-start gap-7 lg:grid-cols-[minmax(0,1fr)_420px]">
    <section className="panel p-5 sm:p-8">
     {step===0&&<ProductPicker value={data.productType} onChoose={choose}/>}
     {step===1&&<DesignForm data={data} product={product} update={update}/>}
     {step===2&&<SetupForm data={data} update={update} error={error}/>}
     {step===3&&<Review data={data}/>}
     {step===4&&<Summary data={data}/>}
     <div className="mt-8 flex flex-wrap items-center justify-between gap-3 border-t border-[#303745] pt-6">
      <button onClick={()=>setStep(v=>Math.max(0,v-1))} disabled={!step} className="btn secondary disabled:invisible"><ChevronLeft size={17}/>Back</button>
      {step<4?<button onClick={next} className="btn primary">{step===3?"Review order":"Continue"}<ChevronRight size={17}/></button>:<button onClick={add} className="btn primary"><Nfc size={18}/>Add Custom NFC to Cart</button>}
     </div>
    </section>
    <aside className="space-y-4 lg:sticky lg:top-28"><Preview data={data}/><div className="panel p-5"><div className="flex items-center justify-between"><div><span className="muted text-xs">One Price. Fully Yours.</span><b className="block text-2xl">{peso(data.unitPrice)}</b></div><span className="badge">Programming FREE</span></div><p className="mt-3 text-xs text-[#77e5ad]">Personalization Included</p><p className="muted mt-1 text-xs">Estimated student price {peso(studentPrice(data.unitPrice))}. Verification may be required.</p></div></aside>
   </div>
  </div>
 </div>
}

function Progress({step}:{step:number}){return <nav aria-label="Customization progress" className="flex overflow-x-auto pb-2">{steps.map((x,i)=><button onClick={()=>i<=step&&setTimeout(()=>{},0)} aria-current={i===step?"step":undefined} className={"flex min-w-[130px] flex-1 items-center text-left text-xs "+(i<=step?"text-white":"text-gray-600")} key={x}><span className={"mr-2 grid h-8 w-8 shrink-0 place-items-center rounded-full border "+(i<step?"border-[#77e5ad] bg-[#77e5ad] text-black":i===step?"border-[#77e5ad] text-[#77e5ad]":"border-[#303745]")}>{i<step?<Check size={15}/>:i+1}</span>{x}{i<4&&<span className={"mx-3 h-px min-w-4 flex-1 "+(i<step?"bg-[#77e5ad]":"bg-[#303745]")}/>}</button>)}</nav>}

function ProductPicker({value,onChoose}:{value:NFCProductType;onChoose:(id:NFCProductType)=>void}){return <><p className="eyebrow">Step 1</p><h2 className="mt-2 text-3xl font-black">Choose your NFC product</h2><p className="muted mt-2">Every option includes a writable NFC chip and free programming.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{products.map(p=><button key={p.id} onClick={()=>onChoose(p.id)} className={"rounded-2xl border p-5 text-left "+(value===p.id?"border-[#77e5ad] bg-[#77e5ad]/10 ring-1 ring-[#77e5ad]":"border-[#303745] hover:border-[#596273]")}><div className="flex justify-between gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#173225] text-[#77e5ad]"><Nfc/></span>{value===p.id&&<Check className="text-[#77e5ad]"/>}</div><b className="mt-4 block">{p.name}</b><span className="mt-1 block text-sm text-[#77e5ad]">From {peso(p.price)}</span><p className="muted mt-2 text-xs leading-5">{p.description}</p><div className="mt-3 flex flex-wrap gap-1">{p.colors.slice(0,3).map(c=><span className="rounded-full bg-white/5 px-2 py-1 text-[10px]" key={c}>{c}</span>)}</div></button>)}</div></>}

function DesignForm({data,product,update}:{data:NFCCustomization;product:(typeof products)[number];update:(x:Partial<NFCCustomization>)=>void}){
 const bracelet=["bracelet","couple"].includes(data.productType), card=["card","premium-card"].includes(data.productType), stand=data.productType==="stand";
 return <><p className="eyebrow">Step 2</p><h2 className="mt-2 text-3xl font-black">Design it your way</h2><div className="mt-7 grid gap-5 sm:grid-cols-2"><Select label="Color" value={data.color} options={product.colors} onChange={color=>update({color})}/><Select label="Style" value={data.style} options={product.styles} onChange={style=>update({style})}/>
 {card&&<><Field label="Full name" value={data.name} onChange={name=>update({name})} max={40} placeholder="Juan Dela Cruz"/><Field label="Job title" value={data.title} onChange={title=>update({title})} max={40} placeholder="Graphic Designer"/><Field label="Company / business" value={data.company} onChange={company=>update({company})} max={40} placeholder="JDC Creative Studio"/><Field label="Short tagline" value={data.text} onChange={text=>update({text})} max={55} placeholder="Ideas made visible."/><Select label="Background" value={data.background} options={["Midnight","Emerald","Light","Gradient"]} onChange={background=>update({background})}/><Select label="Text alignment" value={data.alignment} options={["left","center"]} onChange={alignment=>update({alignment:alignment as "left"|"center"})}/><Select label="Text style" value={data.font} options={["Modern","Classic","Bold"]} onChange={font=>update({font:font as NFCCustomization["font"]})}/><Select label="Editing side" value={data.side} options={["front","back"]} onChange={side=>update({side:side as "front"|"back"})}/></>}
 {bracelet&&<><Field label="Initials / engraving" value={data.initials} onChange={initials=>update({initials})} max={10} placeholder="KRS"/><Field label="Short text" value={data.text} onChange={text=>update({text})} max={18} placeholder="Always connected"/><Select label="Symbol" value={data.symbol} options={["None","Lightning","Heart","Star","Spark"]} onChange={symbol=>update({symbol})}/></>}
 {!card&&!bracelet&&<><Field label={stand?"Business name":"Name / initials"} value={data.name} onChange={name=>update({name})} max={stand?35:24} placeholder={stand?"KADA Cafe":"KRS"}/><Field label={stand?"Short call to action":"Contact / short text"} value={data.text} onChange={text=>update({text})} max={stand?32:28} placeholder={stand?"Tap to View Menu":"Emergency: 0917..."}/><Select label="Icon" value={data.symbol} options={["None","Star","Heart","Contact","Pet"]} onChange={symbol=>update({symbol})}/></>}
 <div className="sm:col-span-2"><Uploader data={data} update={update}/></div>
 {card&&<label className="flex items-center gap-3 text-sm sm:col-span-2"><input type="checkbox" checked={data.qrCode} onChange={e=>update({qrCode:e.target.checked})} className="h-4 w-4 accent-[#77e5ad]"/><QrCode size={18}/>Add an optional QR code</label>}</div></>
}

function Uploader({data,update}:{data:NFCCustomization;update:(x:Partial<NFCCustomization>)=>void}){
 const upload=(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){alert("Choose a JPG, JPEG, PNG, or WebP image.");return}if(file.size>4*1024*1024){alert("Image must be 4 MB or smaller.");return}const reader=new FileReader();reader.onload=()=>update({imageName:file.name,imageDataUrl:String(reader.result)});reader.readAsDataURL(file)};
 return <div><b className="mb-2 block text-sm">Photo, logo, or artwork</b><div className="rounded-2xl border border-dashed border-[#405044] bg-[#0c1016] p-5">{data.imageDataUrl?<div className="flex flex-wrap items-center gap-4"><img src={data.imageDataUrl} alt="Uploaded design preview" className="h-20 w-20 rounded-xl object-cover"/><div className="min-w-0 flex-1"><b className="block truncate text-sm">{data.imageName}</b><p className="muted mt-1 text-xs">Stored in this browser for this customization only.</p><div className="mt-3 flex flex-wrap gap-2"><label className="btn secondary !min-h-0 !px-3 !py-2 text-xs">Replace<input className="sr-only" type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" onChange={upload}/></label><button onClick={()=>update({imageName:undefined,imageDataUrl:undefined})} className="btn secondary !min-h-0 !px-3 !py-2 text-xs text-red-300"><Trash2 size={14}/>Remove</button></div></div></div>:<label className="flex cursor-pointer flex-col items-center py-5 text-center"><ImagePlus className="text-[#77e5ad]"/><b className="mt-3">Upload an image</b><span className="muted mt-1 text-xs">JPG, PNG, or WebP � up to 4 MB</span><span className="btn secondary mt-4"><Upload size={16}/>Choose file</span><input className="sr-only" type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" onChange={upload}/></label>}
 {data.imageDataUrl&&<div className="mt-5 grid gap-4 sm:grid-cols-3"><Range label="Scale" value={data.imageScale} min={60} max={160} onChange={imageScale=>update({imageScale})}/><Range label="Horizontal" value={data.imageX} min={0} max={100} onChange={imageX=>update({imageX})}/><Range label="Vertical" value={data.imageY} min={0} max={100} onChange={imageY=>update({imageY})}/></div>}</div></div>
}

function SetupForm({data,update,error}:{data:NFCCustomization;update:(x:Partial<NFCCustomization>)=>void;error:string}){return <><p className="eyebrow">Step 3</p><h2 className="mt-2 text-3xl font-black">FREE NFC Programming Included</h2><p className="muted mt-2">Choose the convenient option for you. Neither option changes the price.</p><div className="mt-7 grid gap-3">{[{id:"self",title:"ill Program It Myself",copy:"Receive your NFC product ready for programming using a compatible NFC-writing application. You can program or change supported content later."},{id:"kada",title:"KADA Programs It For Me  FREE",copy:"Send us the link you want your NFC to open, and KADA Tech will program it before delivery at no additional cost."}].map(x=><button key={x.id} onClick={()=>update({setup:x.id as "self"|"kada"})} className={"rounded-2xl border p-5 text-left "+(data.setup===x.id?"border-[#77e5ad] bg-[#77e5ad]/10 ring-1 ring-[#77e5ad]":"border-[#303745]")}><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><b>{x.title}</b>{x.id==="kada"&&<span className="badge">RECOMMENDED</span>}</div><p className="muted mt-2 text-sm leading-6">{x.copy}</p></div><span className={"mt-1 grid h-6 w-6 shrink-0 place-items-center rounded-full border "+(data.setup===x.id?"border-[#77e5ad] bg-[#77e5ad] text-black":"border-[#596273]")}>{data.setup===x.id&&<Check size={14}/>}</span></div></button>)}</div>
 {data.setup==="kada"&&<div className="mt-7 rounded-2xl border border-[#303745] bg-[#0c1016] p-5"><h3 className="font-bold">What should it open?</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><Select label="Destination type" value={data.destinationType} options={destinations} onChange={destinationType=>update({destinationType})}/><Field label="HTTPS destination URL" value={data.destinationUrl} onChange={destinationUrl=>update({destinationUrl})} placeholder="https://example.com/juan"/>{["Business Information","Contact Information"].includes(data.destinationType)&&<><Field label="Phone (optional)" value={data.programmingFields.phone||""} onChange={phone=>update({programmingFields:{...data.programmingFields,phone}})} placeholder="+63 917 123 4567"/><Field label="Email (optional)" value={data.programmingFields.email||""} onChange={email=>update({programmingFields:{...data.programmingFields,email}})} placeholder="juan@example.com"/></>}</div><p className="muted mt-4 text-xs">KADA stores the destination information with this demo cart item only. The website does not write the NFC chip.</p>{error&&<p role="alert" className="mt-3 text-sm text-red-400">{error}</p>}</div>}
 {data.setup==="self"&&<div className="mt-6 rounded-xl border border-[#29523e] bg-[#173225] p-4 text-sm text-[#b9f5d6]"><b>Good to know:</b> compatible writable products can be updated later with a compatible NFC-writing app, provided the chip has not been permanently locked.</div>}</>}

function Preview({data}:{data:NFCCustomization}){const bg=data.background==="Light"?"#e9eee9":data.background==="Emerald"?"#173b2c":data.background==="Gradient"?"linear-gradient(135deg,#0c1016,#286245)":"#090d12";const text=data.background==="Light"?"#09110d":"white";const image=data.imageDataUrl&&<img src={data.imageDataUrl} alt="" className="absolute h-24 w-24 rounded-xl object-cover opacity-90" style={{left:data.imageX+"%",top:data.imageY+"%",transform:"translate(-50%,-50%) scale("+(data.imageScale/100)+")"}}/>;return <div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-[#303745] px-5 py-4"><div><p className="eyebrow">Live preview</p><b>{data.productName}</b></div><span className="text-xs text-[#77e5ad]"><Nfc className="inline" size={16}/> NFC ready</span></div><div className="grid min-h-[330px] place-items-center overflow-hidden bg-[#0c1016] p-6">
 {data.productType==="card"?<div className="relative aspect-[1.59] w-full max-w-[360px] overflow-hidden rounded-2xl border border-white/20 p-6 shadow-2xl" style={{background:bg,color:text,textAlign:data.alignment,fontFamily:data.font==="Classic"?"Georgia,serif":"Arial,sans-serif",fontWeight:data.font==="Bold"?800:400}}>{image}<div className="relative z-10 flex h-full flex-col justify-end"><span className="text-[10px] font-bold tracking-[.22em] text-[#77e5ad]">KADA NFC � {data.side.toUpperCase()}</span><strong className="mt-2 text-xl">{data.name||"YOUR NAME"}</strong><span className="text-sm opacity-80">{data.title||"Your title"}</span><span className="text-xs opacity-60">{data.company||data.text||"Your story, one tap away."}</span></div>{data.qrCode&&<QrCode className="absolute right-5 top-5 z-10" size={42}/>}</div>:data.productType==="bracelet"?<div className="relative h-28 w-full max-w-sm rounded-[60px] border-[18px] border-[#262d37] bg-[#10141c] shadow-2xl"><b className="absolute inset-0 grid place-items-center text-lg text-[#77e5ad]">{data.initials||"KRS"} {data.symbol!=="None"&&data.symbol.split(" ")[0]}</b></div>:<div className={"relative grid place-items-center overflow-hidden border border-white/20 bg-[#151b20] p-7 text-center shadow-2xl "+(data.productType==="tag"?"h-52 w-44 rounded-[40%]":data.productType==="stand"?"h-64 w-48 rounded-xl":"h-48 w-48 rounded-[36px]")}>{image}<div className="relative z-10"><Nfc className="mx-auto text-[#77e5ad]"/><b className="mt-3 block text-lg">{data.name||data.productName.replace("KADA NFC ","")}</b><span className="muted mt-1 block text-xs">{data.text||"Tap to connect"}</span></div></div>}</div></div>}

function Review({data}:{data:NFCCustomization}){return <><p className="eyebrow">Step 4</p><h2 className="mt-2 text-3xl font-black">Check your creation</h2><p className="muted mt-2">The preview updates with every choice. Confirm the physical design and tap destination before review.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><Info label="Product" value={data.productName}/><Info label="Color / style" value={data.color+" � "+data.style}/><Info label="Personalization" value={data.name||data.initials||data.text||"No text added"}/><Info label="Image / logo" value={data.imageName||"Not uploaded"}/><Info label="QR code" value={data.qrCode?"Yes":"No"}/><Info label="NFC setup" value={data.setup==="kada"?"KADA programs it  FREE":"Self-programming"}/></div></>}
function Summary({data}:{data:NFCCustomization}){return <><p className="eyebrow">Custom NFC order</p><h2 className="mt-2 text-3xl font-black">Ready to make it yours?</h2><div className="mt-7 rounded-2xl border border-[#303745] bg-[#0c1016] p-5"><Info label="Order item" value={data.productName}/><Info label="Color / style" value={data.color+" � "+data.style}/><Info label="Name / engraving" value={data.name||data.initials||""}/><Info label="Custom text" value={data.text||""}/><Info label="Uploaded design" value={data.imageName||"None"}/><Info label="QR code" value={data.qrCode?"Yes":"No"}/><Info label="NFC programming" value={data.setup==="kada"?"KADA programmed":"Customer programmed"}/>{data.setup==="kada"&&<><Info label="Destination type" value={data.destinationType}/><Info label="URL" value={data.destinationUrl}/></>}<Info label="Programming fee" value="FREE" accent/><div className="mt-4 flex justify-between border-t border-[#303745] pt-5 text-xl"><b>Total</b><b>{peso(data.unitPrice)}</b></div></div><p className="muted mt-4 text-xs">This structured customization is saved with your cart item and is ready for future Shopify line item properties or another order backend.</p></>}
function Info({label,value,accent}:{label:string;value:string;accent?:boolean}){return <div className="flex gap-4 border-b border-[#202633] py-3 text-sm last:border-0"><span className="muted min-w-28">{label}</span><b className={"ml-auto text-right "+(accent?"text-[#77e5ad]":"")}>{value}</b></div>}
function Field({label,value,onChange,placeholder,max}:{label:string;value:string;onChange:(x:string)=>void;placeholder:string;max?:number}){return <label className="text-sm"><b className="mb-2 flex justify-between">{label}{max&&<span className="muted font-normal">{value.length}/{max}</span>}</b><input className="field" value={value} maxLength={max} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(x:string)=>void}){return <label className="text-sm"><b className="mb-2 block">{label}</b><select className="field" value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Range({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(x:number)=>void}){return <label className="text-xs"><b className="mb-2 flex justify-between">{label}<span className="muted">{value}%</span></b><input className="w-full accent-[#77e5ad]" type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
