"use client";
import { PackageCheck, Plus } from "lucide-react";
import { products } from "@/data/products";
import { bundleDefinitions, calculateBundle, businessNfcBundle } from "@/data/pricing";
import { peso } from "@/lib/helpers";
import Link from "next/link";

export function ValueBundles(){

 return <section className="section border-y border-[#202633] bg-[#0c1016]"><div className="container"><p className="eyebrow">More value, fewer decisions</p><h2 className="mt-2 text-4xl font-black">Useful KADA bundles.</h2><p className="muted mt-3 max-w-2xl">Relevant setup combinations with savings calculated from current catalog prices. No inflated bundle totals.</p><div className="mt-8 grid gap-4 lg:grid-cols-3">{bundleDefinitions.map(bundle=>{const items=bundle.productIds.map(id=>products.find(p=>p.id===id)).filter(Boolean) as typeof products;const totals=calculateBundle(items.map(p=>p.price),bundle.discountRate);return <article className="panel flex flex-col p-6" key={bundle.id}><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#173225] text-[#77e5ad]"><PackageCheck/></span><div><b>{bundle.name}</b><p className="muted text-xs">{items.length} matched products</p></div></div><ul className="muted mt-5 space-y-2 text-sm">{items.map(p=><li key={p.id}>+ {p.name}</li>)}</ul><div className="mt-6 space-y-2 border-t border-[#303745] pt-5 text-sm"><div className="flex justify-between"><span className="muted">Buy separately</span><del>{peso(totals.separate)}</del></div><div className="flex justify-between text-lg"><b>Bundle price</b><b>{peso(totals.price)}</b></div><div className="flex justify-between text-[#77e5ad]"><b>You save</b><b>{peso(totals.savings)}</b></div></div><Link href={`/shop?bundle=${bundle.id}`} className="btn primary mt-5 w-full"><Plus size={17}/>View bundle items</Link><p className="muted mt-2 text-center text-[10px]">Bundle checkout pricing is a frontend preview pending backend integration.</p></article>})}</div><article className="panel mt-4 grid items-center gap-5 p-6 md:grid-cols-[1fr_auto]"><div><p className="eyebrow">Personalization and programming included</p><h3 className="mt-2 text-xl font-bold">KADA Business NFC Starter</h3><p className="muted mt-2 text-sm">Custom NFC Card + NFC Desk Stand + NFC Keychain.</p></div><div className="min-w-64 text-sm"><div className="flex justify-between gap-8"><span className="muted">Buy separately</span><del>{peso(businessNfcBundle.separate)}</del></div><div className="mt-2 flex justify-between text-lg"><b>Bundle price</b><b>{peso(businessNfcBundle.price)}</b></div><div className="mt-1 flex justify-between text-[#77e5ad]"><b>You save</b><b>{peso(businessNfcBundle.savings)}</b></div><Link href="/nfc-studio" className="btn secondary mt-4 w-full">Customize NFC</Link></div></article></div></section>
}
